
pool:
  vmImage: ubuntu-latest
  
pr: none

trigger:
  branches:
    include:
      - master


variables:
  minorVersion: 1
  majorVersion: 0

parameters:
  - name: projectNames
    type: object
    default:
      - Maui.CodeGenerator.Core
      - Maui.CodeGeneratorHelpers
  

name: $(majorVersion).$(minorVersion).$(Build.BuildId)

stages:

  - stage: Pack
    displayName: Pack Nugets

    jobs:

      - job: Build

        steps:
          
          - ${{ each project in parameters.projectNames }}:
            - script: dotnet pack ${{ project }}
                      -o $(Build.ArtifactStagingDirectory)/packed
                      -c release
                      -p:PackageVersion=$(Build.BuildNumber)
              displayName: Packing ${{ project }}
              workingDirectory: src


          # - task: DotNetCoreCLI@2
          #   inputs:
          #     projects: |
          #       Maui.CodeGenerator.Core
          #       Maui.CodeGeneratorHelpers
          #     command: pack
          #     versioningScheme: byBuildNumber
          #     modifyOutputPath: true
          #     workingDirectory: src
          #     configuration: release
          #     arguments: -o $(Build.ArtifactStagingDirectory)/packed

          - publish: $(Build.ArtifactStagingDirectory)/packed
            displayName: Publish
            artifact: Packed

  - stage: Deploy
    displayName: Deploy to Nuget

    jobs:
      
      - job: Deploy
        steps:

          - download: current
            artifact: Packed

          - checkout: none

          - task: NuGetCommand@2
            displayName: Internal nuget upload
            inputs:
              command: 'push'
              packagesToPush: '$(Pipeline.Workspace)/Packed/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: NuGet


