
pool:
  vmImage: ubuntu-latest
  
pr: none

trigger:
  branches:
    include:
      - master


variables:
  projectNames: |
    Maui.CodeGenerator.Core
    Maui.CodeGeneratorHelpers
  minorVersion: 1
  majorVersion: 0

name: $(minorVersion).$(minorVersion).$(Build.BuildId)

stages:

  - stage: Pack
    displayName: Pack Nugets

    jobs:

      - job: Build

        steps:

          - script: dotnet pack -p Maui.CodeGenerator.Core 
                    -o $(Build.ArtifactStagingDirectory)/packed
                    -c release
                    -p:PackageVersion=$(Build.BuildName)
            displayName: Packing Maui.CodeGenerator.Core
            workingDirectory: src

          # - task: DotNetCoreCLI@2
          #   inputs:
          #     projects: |
          #       Maui.CodeGenerator.Core
          #       Maui.CodeGeneratorHelpers
          #     command: pack
          #     versioningScheme: byBuildNumber
          #     modifyOutputPath: true
          #     workingDirectory: src
          #     configuration: release
          #     arguments: -o $(Build.ArtifactStagingDirectory)/packed

          - publish: $(Build.ArtifactStagingDirectory)/packed
            displayName: Publish
            artifact: Packed



